### ISSUE TITLE
Add co-representation of space group

### ISSUE THREAD

**Issue by lan496** [spglib/spgrep#12]

**Comment by hongyi-zhao** [comment]
Has this feature been implemented?

Side remark: [co-representation](https://en.wikipedia.org/wiki/Corepresentations_of_unitary_and_antiunitary_groups) is mainly used in the theoretical study of [magnetic structure](https://en.wikipedia.org/wiki/Magnetic_structure) but is also relevant to [particle physics](https://en.wikipedia.org/wiki/Particle_physics) due to [CPT symmetry](https://en.wikipedia.org/wiki/CPT_symmetry), where [antilinear](https://en.wikipedia.org/wiki/Antilinear_map) operators are included in the group.

On the other hand, if we study a system in which the influence of spin orbit coupling and anti-unitary operator should be considered simultaneously. In this case, [the irreducible co-representations of the (Double) Magnetic Space Groups](https://www.cryst.ehu.es/cgi-bin/cryst/programs/corepresentations.pl) is needed. So I also suggest add this feature into this package.

**Comment by lan496** [comment]
Thank you for your comment and resources!
As an initial motivation of this package to me is on-the-fly symmetry analysis of phonon, I've not implemented this feature yet. So, I will work on it in the future.

**Comment by hongyi-zhao** [comment]
I also want to implement on the fly symmetry analysis based on [GAP](https://www.gap-system.org/) and its crystallography related packages, such as [carat](https://www.gap-system.org/Packages/caratinterface.html), and [cryst](https://www.gap-system.org/Packages/cryst.html). Though I have worked hard for some time, but there is still little progress.

**Comment by lan496** [comment]
Unfortunately, I have little experience with GAP (only sometimes use cryst package).
That being said, I think [spgrep's formulation pages](https://spglib.github.io/spgrep/formulation.html) may help to implement the irreps-search algorithm in other languages.

**Comment by hongyi-zhao** [comment]
Thank you for your information. I'll try to learn it.

BTW, currently, I come across a problem that puzzles me when computing Wyckoff using the cryst package, I'm not sure if you would like to discuss the problem with me in private.

Best,
Zhao
