### ISSUE TITLE
Missing data file in lattice vibration example

### ISSUE THREAD

**Issue by ml-evs** [spglib/spgrep#77]
Hi there, I'm reviewing this repository for JOSS. Everything else looks great to me, but I am unable to run `examples/lattice_vibration.py` as the file `phonopy_mp-2998.yaml.xz` is missing, and I couldn't find it in the raw data from http://phonondb.mtl.kyoto-u.ac.jp/ph20180417/d002/mp-2998.html. Is this an oversight, or am I missing something?

**Comment by lan496** [comment]
@ml-evs Thank you for examining the example script. I have fixed the location for phonopy data `phonopy_mp-2998.yaml.xz`. Can you check if the issue is solved at the HEAD of develop branch (https://github.com/spglib/spgrep/commit/161fd31ea469702083934cecbcf50fb662d934ab)?
Actually, xz-format phonopy datum are stored in <http://phonondb.mtl.kyoto-u.ac.jp/xz-files/> in phonondb.

**Comment by ml-evs** [comment]
Thanks, that works for me now! Indeed, I was running the script rather than the Jupyter notebook, which probably always worked.
